version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: 'Dockerfile.web'
    ports:
      - "8000:8000"
  nginx:
    build:
      context: .
      dockerfile: 'Dockerfile.nginx'
    ports:
      - "3000:80"